////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

= Maven Shade Plugin Extensions

This project contains a collection of https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html[resource transformer]s for the Apache Maven Shade Plugin that allows you to use additional Log4j 2.x Core component modules.

[#log4j-plugin-cache-transformer]
== Log4j Plugin Descriptor Transformer

A
https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html[resource transformer]
for the
https://maven.apache.org/plugins/maven-shade-plugin/index.html[Apache Maven Shade Plugin]
that merges `Log4j2Plugins.dat` plugin caches from all the jars containing Log4j 2.x Core components.

This transformer was formerly available at
https://github.com/edwgiz/maven-shaded-log4j-transformer[edwgiz/maven-shaded-log4j-transformer]
and was donated to the Apache Software Foundation by its author.

[TIP]
====
If you are a Gradle user, you can use the
https://gradleup.com/shadow/configuration/merging/#merging-log4j2-plugin-cache-files-log4j2plugins-dat[equivalent Shadow Gradle Plugin transformer].
====

[#log4j-plugin-cache-transformer-usage]
=== Usage

This resource transformer is usually used together with the `ManifestResourceTransformer` and `ServicesResourceTransformer` to integrate Log4j 2.x libraries in a shaded JAR.

A typical configuration is:

[source,xml,subs="+attributes"]
----
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-shade-plugin</artifactId>
  <version>3.4.1</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-transform-maven-shade-plugin-extensions</artifactId>
      <version>{project-version}</version>
    </dependency>
  </dependencies>
  <executions>
    <execution>
      <id>shade-jar-with-dependencies</id>
      <phase>package</phase>
      <goals>
        <goal>shade</goal>
      </goals>
      <configuration>
        <transformers>
          <transformer implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer"/>
          <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
          <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
            <manifestEntries>
              <Multi-Release>true</Multi-Release>
            </manifestEntries>
          </transformer>
        </transformers>
      </configuration>
    </execution>
  </executions>
</plugin>
----
