staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/transform


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 6339
# - Commit ID: 409760ce2bde1af858e7df2685009f1fac5589a5
# - Timestamp: 2025-08-07T19:27:42Z
