staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/transform


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 10732
# - Commit ID: 166ca117ddd9b54b7bd700c21c93bfb6a418d396
# - Timestamp: 2025-03-05T11:43:57Z
