staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/transform


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 13010
# - Commit ID: 3abb6b294d250d2b0cb5b6944b7ed94b1ed0e891
# - Timestamp: 2025-01-23T12:03:26Z
