publish:
  profile: ~
  whoami: main-site-pro-out
  subdir: content/log4j/transform


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 17141
# - Commit ID: 4c388196e386cdc19f97f590c703281748e2dcb8
# - Timestamp: 2024-10-31T05:44:26Z
