////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////
[#log4j-codegen]
= Apache Log4j code generator

include::_constants.adoc[]

The `log4j-codegen` artifacts contains tools to generate logging-related code.

[#CustomLoggers]
== Generating Source Code for a Custom Logger Wrapper

Common Log4j usage is to get an instance of the `Logger` interface from
the `LogManager` and call the methods on this interface. However, the
custom log Levels are not known in advance, so Log4j cannot provide an
interface with convenience methods for these custom log Levels.

To solve this, Log4j ships with a tool that generates source code for a
Logger wrapper. The generated wrapper class has convenience methods for
each custom log level, making custom levels just as easy to use as the
built-in levels.

There are two flavors of wrappers: ones that **extend** the Logger API (adding methods to the built-in levels) and ones that **customize** the Logger API (replacing the built-in methods).

When generating the source code for a wrapper class, you need to
specify:

* the fully qualified name of the class to generate
* the list of custom levels to support and their `intLevel` relative
strength
* whether to extend `Logger` (and keep the existing built-in methods) or
have only methods for the custom log levels

You would then include the generated source code in the project where
you want to use custom log levels.

[#ExampleUsage]
== Example Usage of a Generated Logger Wrapper

Here is an example of how one would use a generated logger wrapper with
custom levels DIAG, NOTICE and VERBOSE:

[source,java]
----
// ExtLogger is a generated logger wrapper
import com.mycompany.myproject.ExtLogger;

public class MyService {
    // instead of Logger logger = LogManager.getLogger(MyService.class):
    private static final ExtLogger logger = ExtLogger.create(MyService.class);

    public void demoExtendedLogger() {
        // ...
        logger.trace("the built-in TRACE level");
        logger.verbose("a custom level: a VERBOSE message");
        logger.debug("the built-in DEBUG level");
        logger.notice("a custom level: a NOTICE message");
        logger.info("the built-in INFO level");
        logger.diag("a custom level: a DIAG message");
        logger.warn("the built-in WARN level");
        logger.error("the built-in ERROR level");
        logger.fatal("the built-in FATAL level");
        logger.notice("java 8 lambda expression only executed if NOTICE is enabled: {}", () -> someMethod());
        // ...
    }
    ...
}
----

[#CodeGen]
== Generating Extended Loggers

Use the following command to generate a logger wrapper that adds methods
to the built-in ones:

[source,sh,subs="attributes"]
----
java -jar log4j-core-{project-version}.jar extendedLogger \
    com.mycomp.ExtLogger DIAG=350 NOTICE=450 VERBOSE=550 \
    > com/mycomp/ExtLogger.java
----

This will generate source code for a logger wrapper that has the
convenience methods for the built-in levels _as well as_ the specified
custom levels. The tool prints the generated source code to the console.
By appending " > _filename_" the output can be redirected to a file.

== Generating Custom Loggers

Use the following command to generate a logger wrapper that hides the
built-in levels and has only custom levels:

[source,sh,subs="attributes"]
----
java -jar log4j-core-{project-version}.jar customLogger \
    com.mycomp.MyLogger DEFCON1=350 DEFCON2=450 DEFCON3=550 \
    > com/mycomp/MyLogger.java
----

This will generate source code for a logger wrapper that _only_ has
convenience methods for the specified custom levels, _not_ for the
built-in levels. The tool prints the generated source code to the
console. By appending " > _filename_" the output can be redirected to a
file.
